# version: '3'
# services: 
#   web: 
#     image: jpcastberg/itemview-module:deployment
#     build: ./
#     command: node server/index.js
#     ports:
#       - "80:3001"
#     depends_on:
#       - "jjam-itemview"
#   jjam-itemview:
#     image: "mongo"
#     ports:
#       - "27017:27017"

#For EC2 

version: '3'
services: 
  web: 
    image: philipstout3/header2
    command: node server/index.js
    ports:
      - "80:3001"