--this file was used to keep track of my postgres table creation
CREATE TABLE restaurants (
  id int PRIMARY KEY,
  id_name VARCHAR(10),
  name VARCHAR(50),
  rating DOUBLE PRECISION,
  ratings_num SMALLINT,
  price_min SMALLINT,
  price_max SMALLINT,
  description VARCHAR(1000),
  food_type VARCHAR(50),
  tag_one VARCHAR(50),
  tag_two VARCHAR(50),
  tag_three VARCHAR(50),
  cross_street VARCHAR(50),
  neighborhood VARCHAR(50),
  brunch_hrs VARCHAR(60),
  lunch_hrs VARCHAR(60),
  dinner_hrs VARCHAR(60),
  dining_style VARCHAR(50),
  dress_code VARCHAR(50),
  payment_options VARCHAR(50),
  chef VARCHAR(50),
  entertainment  VARCHAR(50),
  additional_info  VARCHAR(50),
  website VARCHAR(50),
  phone_number VARCHAR(50),
  longitude VARCHAR(50),
  latitude VARCHAR(50),
  street_address VARCHAR(50)
)